name: debug_overlay
description: 'ðŸ› View debug infos and change settings via a central overlay for your app.'
version: 0.1.1
homepage: https://github.com/JonasWanke/debug_overlay

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  black_hole_flutter: ^0.3.0
  collection: ^1.15.0
  data_size: ^0.2.0
  device_info_plus: ^1.0.0
  flutter:
    sdk: flutter
  implicitly_animated_list: ^2.0.0
  meta: ^1.3.0
  package_info_plus: ^1.0.0
  shake: ^1.0.0
  supercharged: ^2.0.0

dev_dependencies:
  extra_pedantic: ^1.3.0
  test: ^1.9.4
